### ISSUE TITLE
read_template_file without untaint causing Security Error

### ISSUE THREAD

**Issue by pboling** [rtomayko/tilt#224]
I am setting $SAFE to 0 in my app. This is a pure Ruby 1.8.7 app (CGI script), not Rails, or even Rack. As I understand it all possible settings of $SAFE will at least cause taintedness in streams, and data read from the file system. Thus I don't understand how Tilt can read a template and use it without untainting it first. I have double and triple checked and I am untainting everything everywhere that I possibly can. So the only explanation I can think of is that Tilt is reading from the file system (see my patch above) and not untainting it (which is what I altered in my patch).

What confuses me though is **how is this working for anyone?** Why doesn't everyone have this issue?

It doesn't seem possible to use tilt & haml without hacking it like this:

````ruby
require 'tilt'
require 'thread'

module Tilt
  class Template
    def initialize(file=nil, line=1, options={}, &block)
      # ... snip
      @default_encoding = @options.delete :default_encoding

      # load template data and prepare (uses binread to avoid encoding issues)
      ########## BELOW LINE IS CHANGED: adds untaint ##########
      @reader = block || lambda { |t| read_template_file.untaint }
      ########## ABOVE LINE IS CHANGED: adds untaint ##########
      @data = @reader.call(self)

      if @data.respond_to?(:force_encoding)
      # ... snip
    end

  end
end
````

I originally thought this was a HAML issue, before I figured out the root cause of the problem.  See: https://github.com/haml/haml/issues/730

**Comment by judofyr** [comment]
Closing this for now. `$SAFE` is very rarely used.
