### ISSUE TITLE
Autodetect Loaded Markups

### ISSUE THREAD

**Issue by whitehat101** [rtomayko/tilt#237]
I'm working on a gem for for a rails app. If the user has the relevant gems loaded up, I'd like to use the Tilt::Template for sprockets, if they don't have it, meh.

[source](https://github.com/whitehat101/angular-rails-templates/blob/master/lib/angular-rails-templates/engine.rb#L9-17):
```ruby
    # try loading common markups
    %w(erb haml liquid md radius slim str textile wiki).
    each do |ext|
      begin
        config.angular_templates.markups << ext if Tilt[ext]
      rescue LoadError
        # They don't have the required library required. Oh well.
      end
    end
```

It seems to work exactly as I hoped, *however* when I tested with Rails 4.1 + Spring, when I start the `rails console` for the first time I get the [autoloading ... in a non thread-safe way](https://github.com/rtomayko/tilt/blob/master/lib/tilt/mapping.rb#L239-240) warning. It doesn't seem to happen with `rails server`, or if spring is disabled.

```
WARN: tilt autoloading 'liquid' in a non thread-safe way; explicit require 'liquid' suggested.
WARN: tilt autoloading 'redcarpet' in a non thread-safe way; explicit require 'redcarpet' suggested.
WARN: tilt autoloading 'rdiscount' in a non thread-safe way; explicit require 'rdiscount' suggested.
WARN: tilt autoloading 'rdiscount' in a non thread-safe way; explicit require 'rdiscount' suggested.
WARN: tilt autoloading 'bluecloth' in a non thread-safe way; explicit require 'bluecloth' suggested.
WARN: tilt autoloading 'kramdown' in a non thread-safe way; explicit require 'kramdown' suggested.
WARN: tilt autoloading 'maruku' in a non thread-safe way; explicit require 'maruku' suggested.
WARN: tilt autoloading 'radius' in a non thread-safe way; explicit require 'radius' suggested.
WARN: tilt autoloading 'redcloth' in a non thread-safe way; explicit require 'redcloth' suggested.
WARN: tilt autoloading 'wikicloth' in a non thread-safe way; explicit require 'wikicloth' suggested.
WARN: tilt autoloading 'creole' in a non thread-safe way; explicit require 'creole' suggested.
```

~~I'm a little confused, because I expected the `require`  to cause the `LoadError` exception, so I'm not sure why it's even getting to the warn block -- I definitely don't have libraries for liquid or radius installed.~~ Rails is pulling Tilt 1.4, and after reading *that* source, I'm not confused.

**Should I just silence the output from this block and move on, or is there a better way to check if there is a library loaded for an extension?**

With HAML or SLIM there is a 1:1 extension to library ratio, and I could check for defined constants, but with markdown there are dozens, and six months from now there could be a new markdown library. I'd like, "if Tilt supports it, we support it" simplicity.

**Comment by judofyr** [comment]
I'm closing this in favor of keeping the discussion in #228. In 2.1 I will implement two methods: one for attempting to lazy load all available template classes, and another for detecting what templates/extensions are available.
