### ISSUE TITLE
allow passing Redcarpet render options through Tilt

### ISSUE THREAD

**Issue by sunaku** [rtomayko/tilt#238]
Hello,

Tilt assumes that Markdown implementations only accept *one* set of
configuration options, whereas Redcarpet accepts *two* of them:

1. [Render options](
      https://github.com/vmg/redcarpet#darling-i-packed-you-a-couple-renderers-for-lunch
    )
2. [Markdown extensions](
      https://github.com/vmg/redcarpet#and-its-like-really-simple-to-use
    )

When you tell Tilt to use Redcarpet for rendering Markdown, it *only*
passes your configuration options as **Markdown extensions** to Redcarpet.
Thus we have no standard way of passing **render options** to Redcarpet
through Tilt.

Please correct this deficiency! :bug: [See here](https://sunaku.github.io/slim-tilt-redcarpet.html) for details and [a workaround](https://sunaku.github.io/slim-tilt-redcarpet.html#solution). :cake:

Thanks for your consideration.

**Comment by jmuheim** [comment]
Is there any progress on this? I would really like to use tables in redcarpet.

**Comment by sunaku** [comment]
@jmuheim Until this is fixed, see [my blog post](https://sunaku.github.io/slim-tilt-redcarpet.html) for a workaround. :ghost:

**Comment by judofyr** [comment]
Merged in 43bcfa98d97e85188cb16efa986587f8b51667d8
