### ISSUE TITLE
2.0.2 Release?

### ISSUE THREAD

**Issue by josephholsten** [rtomayko/tilt#247]
I've got users who could really use the JSON input support for `tilt(1)`. Think we could have a release?

**Comment by judofyr** [comment]
I consider `tilt(1)` to be a secondary tool and such a change doesn't require a minor increment. The version number is mainly for the library. You should generally not depend on `tilt(1)` following any kind of SemVer-ish system.

As for 2.0.2: Yes! I should clean up the issue tracker and release it!

**Comment by judofyr** [comment]
Reminder to self: Don't even try to close this before CHANGELOG is updated. And VERISON.

**Comment by pinfieldharm** [comment]
It's been about a year...any plans on releasing this? Would like to use the babel support.

**Comment by judofyr** [comment]
Yeah. I really do want to release. I just need to find time for it. Before Christmas would be nice. You can always point your Gemfile to the Git repo though.

**Comment by judofyr** [comment]
Done: b0a320e21930da4ef850ad50c09af93c16ed0bae

https://rubygems.org/gems/tilt/versions/2.0.2

**Comment by pinfieldharm** [comment]
Hooray! Thanks!
