### ISSUE TITLE
Backport slim support to 1.x

### ISSUE THREAD

**Issue by seuros** [rtomayko/tilt#248]
Right now, if we want to use tilt and sprocket in the same application, we can use only 1.x version due to sprocket's dependencies.
```
sprockets (2.12.0)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
```
unfortunately the 1.x versions don't support Slim. 
```
Option :escape_html is not supported by Slim::Engine
Option :escape_attrs is not supported by Slim::Engine
```
It is possible to backport Slim support to 1.5 version ?

**Comment by judofyr** [comment]
Closing this since @minad says Slim works with all Tilt versions.

Please comment or re-open if this is still an issue.

**Comment by minad** [comment]
if travis says so :)
