### ISSUE TITLE
Make Tilt::Cache thread-safe

### ISSUE THREAD

**Issue by kushkella** [rtomayko/tilt#260]
Right now Tilt::Cache is just a hash. It returns the value if present, otherwise stores the value and then returns it. This behavior is not thread-safe and makes Tilt::Cache unusable in multi-threaded environment. I think we should implement something like this https://github.com/rails/rails/blob/714a38217e884418d635435eb658ae7347d08dd7/activesupport/lib/active_support/cache/memory_store.rb

I'm not saying that we should add all the pruning and add TTLs but while storing and retrieving objects, we should use a lock to make sure the operation is thread safe. Thanks!

**Comment by kushkella** [comment]
I think this generally solves the issue. Any updates?

**Comment by judofyr** [comment]
I'm hesitant to change an API that has never been thread-aware:

1. Those who care about threading issues have already added a Mutex. Another Mutex could cause performance issues.
2. Tilt::Cache has always been a very simple API to show how you can add template caching. I don't want it to be a fully-featured caching API; everyone has different constraints and use-cases.

Thoughts?

**Comment by tommay** [comment]
My thought would be either to get rid of it or at least document its
deficiencies so people don't get suckered into using it: it's not
thread-safe, it's size isn't bounded, the keys should not be mutated;
anything else?

**Comment by judofyr** [comment]
> it's not thread-safe, it's size isn't bounded, the keys should not be mutated.

That's about it. I'd accept a documentation patch.

**Comment by judofyr** [comment]
This was fixed (that is, properly documented) in #266.
