### ISSUE TITLE
How should Tilt proceed?

### ISSUE THREAD

**Issue by judofyr** [rtomayko/tilt#264]
Hi folks,

People keep asking for adding new template classes in Tilt, and I don't have the capacity to keep them all green in Travis. There's a bunch of issues in the issue tracker now, and I want to clear them all out for a new release, but it's so difficult when it can take several *days* to debug why some template engines are wonky on various Ruby implementations.

So, I'm proposing this:

- I will start accepting new template classes as long as there's someone willing to maintain it. That means: Commit access + responsibility for keeping the build green.
- If a template class loses its maintainer I will move it out of the test matrix such that build failures in that template class doesn't break the whole build.
- I will be better at releasing small fixes in template classes.
- I'm still very much in favor of having template engines include their own template classes.
- **Added:** Changes in template classes can't claim a new minor release. It's up to the maintainer to keep compatibility across minor releases. If several maintainers want to break compatibility, we'll schedule a new minor release and release them all at once.

Thoughts?

If you're a consumer of the Tilt API in *any* way, I'd also love to hear other thoughts/complaints/opinions.

/cc @josh, @rtomayko, @mislav, @djanowski, @rue, @nesquena, @DAddYE, @apotonick, @brianmario, @rkh, @apohllo, @argent-smith, @fibric, @jeremyevans, @jodosha, @zzak.

**Comment by jodosha** [comment]
@judofyr Thanks for starting this discussion and thank you on behalf of all the Ruby ecosystem for maintaining Tilt.

> I will start accepting new template classes as long as there's someone willing to maintain it. That means: Commit access + responsibility for keeping the build green.

What happens to the current 30+ template engines? Do they will be supported by Tilt Core, or do they need a maintainer otherwise they will disappear?

**Comment by judofyr** [comment]
I will maintain a subset of them. Unmaintained template classes will not be disappear. Pull requests will be accepted liberally and I will not care about whether or not it breaks the unmaintained-build.

**Comment by jeremyevans** [comment]
@judofyr What you've proposed sounds good to me.

**Comment by jodosha** [comment]
@judofyr Have you considered that Tilt contributors may disappear after some time? According to your plan, if that template engine is causing a red build, it will be removed from the build and, I guess, from the Tilt gem. Now, this can cause problems to apps that depend on it.

Let's say, I offer my help to maintain HAML, then I won't do it anymore. What happens to apps that are using HAML via Tilt if you remove support for it?

In a previous discussion that we had here, you mentioned the idea of externalize Tilt support. If I'm the author of template engine (`foo`) and I want my gem to be compatible with Tilt, then I must provide a `tilt/foo` extension that will ship the integration code. In this way Tilt can have a smaller and maintanable codebase. Did you rejected this idea? If so, why? :smile:

**Comment by judofyr** [comment]
@jodosha: They will be out of the build (at Travis), but still in the gem.

You can still maintain Tilt-integration code in your own template engine (and I recommend that of course!). You can also send a pull-request and we will add it [here](https://github.com/rtomayko/tilt/blob/8db8ed102e727790068f734fc1485113429c7881/lib/tilt.rb#L136-L139) so it will be automatically detected as well. The main change from this issue is that I will not fight against people adding more stuff to Tilt. If template engines authors *don't* want to bother with Tilt integration I will let other people add template classes to Tilt to support it. I will accept both un-maintained template classes and maintained template classes.

It's probably better to call it "community maintained" and "contributor maintained".

Contributor maintained: The test suite will be part of Tilt's official test suite which must be green before a release. This person will handle issues/pull-requests concerned with this template classes. They can also fix regular bugs as well.

Community maintained: The code and tests live in this repo. It's included in releases as well. However, if the tests break the build, it won't stop a release. I'll accept pull-requests liberally and assume the community handles backwards compatibility and such.

**Comment by jodosha** [comment]
@judofyr Thanks for the explanation. It makes sense :+1:

**Comment by judofyr** [comment]
Aaaand we're green: https://travis-ci.org/rtomayko/tilt/builds/69902058

**Comment by judofyr** [comment]
Okay. I'll work my way through this list https://github.com/rtomayko/tilt/issues?q=is%3Aopen+milestone%3A2.0.2+label%3Aplanned and will release a 2.0.2 with improved template classes.

Closing this issue since I've come to a decent conclusion. Comments are still appreciated.

**Comment by rtomayko** [comment]
@judofyr Your proposal sounds super sane to me. Thanks so much for your time and effort here.

**Comment by rkh** [comment]
👍🏾 sounds good to me
