### ISSUE TITLE
Erubis templates are not working in JRuby 9.0.1.0

### ISSUE THREAD

**Issue by PetrKaleta** [rtomayko/tilt#270]
Let's say, we have super simple `template.html.erb` (no logic inside, just `foo`)
```
foo
```

Once upgraded to JRuby 9.0.1.0 then Erubis template rendering stopped working

```ruby
Tilt::ERBTemplate.new('views/template.html.erb').render # => "foo"
Tilt::ErubisTemplate.new('views/template.html.erb').render # => nil
```

**Comment by judofyr** [comment]
Verified on Travis: https://travis-ci.org/rtomayko/tilt/jobs/84807863

**Comment by judofyr** [comment]
Reported upstream: jruby/jruby#3388.

**Comment by judofyr** [comment]
I've pushed a workaround on a separate branch. You can use this today by changing your Gemfile:

```ruby
gem 'tilt', github: 'rtomayko/tilt', branch: 'erubis-jruby-9010'
```

Apparently it's already been fixed in jruby/jruby#3356 so I will keep this issue/branch open until 9.0.2 is released and then I'll bump the required JRuby-version in `.travis.yml`.

**Comment by PetrKaleta** [comment]
Fabulous, thanks!

**Comment by enebo** [comment]
https://github.com/jruby/jruby/issues/3356 was reported earlier and was fixed at the end of this last week ; so if you want to give master a spin and make sure things are ok now it would give us some sanity for our jruby 9.0.2 release.

**Comment by judofyr** [comment]
The tests are running nicely on 9.0.4 on Travis now, so I assume this is no longer a problem.
