### ISSUE TITLE
Drop 1.8.7 and 1.9 support

### ISSUE THREAD

**Issue by deivid-rodriguez** [rtomayko/tilt#272]
Isn't it about time?

Regards.

**Comment by judofyr** [comment]
Not sure if supporting 1.8.7 holds us back in any way?

**Comment by deivid-rodriguez** [comment]
I downloaded the repo, and I'm having a look at the travis build.

I noticed that about half of the tests are not run because their dependencies are not installed. Some of them are actually broken (the ones depending on redcarpet and rdiscount), but a lot are passing but skipped in CI. I'm not sure why this is done, but the only reason I can think of is to ensure a green build for all versions from 1.8.7. This looks like a bad compromise to me.

I'm not suggesting using +2.0 features, just cleaning up the build a bit to ensure at least that the tests are passing for the newest versions, even if this implies adding 1.8.7 & 1.9.3 to the allowed_failures section.

Hope I explained correctly my concerns.

**Comment by deivid-rodriguez** [comment]
Ok I think I understand now. You don't maintain support for some engines so you don't mind those failing.

**Comment by judofyr** [comment]
Well, now I've removed 1.8 from the Travis build as well. Makes everything much easier :-)

**Comment by deivid-rodriguez** [comment]
Cool! :tada:
