### ISSUE TITLE
Cannot use method with block inside tilt template

### ISSUE THREAD

**Issue by wafcio** [rtomayko/tilt#285]
I have tried to build somethink like ModelView class which will render template with Tilt. Unfortunatelly I have problem with method which we can use with block.

```ruby
require "erb"
require "tilt"

module Component
  def initialize(**options)
    @options = options
  end

  def render
    Tilt.new("template.erb").render(self, @options)
  end

  def sample_method(&block)
    block.call
  end
end
```

```erb
<%= sample_method do %>
  sample
<% end %>
```

```ruby
Component.new(foo: "bar").render
```

```
template.erb:1: syntax error, unexpected ')'
'; _erbout << ( sample_method do ).to_s; _erbout << '
```

Maybe I am doing something wrong.

**Comment by judofyr** [comment]
ERB doesn't typically support block helpers. Rails has an extension to ERB
which handles it. I'm not sure if there's an ERB implementation for Tilt
which supports it.

I've written a template engine which supports it, but it requires some
setup and has a slightly different syntax. It may or may not be what you're
looking for: https://github.com/judofyr/zrb

**Comment by wafcio** [comment]
ok, thanks for explanation

**Comment by judofyr** [comment]
Closing this issue now. Feel free to ask more questions here or open a new issue if you're facing another problem.
