### ISSUE TITLE
No clear separation of template engine supporting `scope` or `locals` or missing `chain` functionality in API

### ISSUE THREAD

**Issue by nonnenmacher** [rtomayko/tilt#287]
I was trying to support *flexible* templates from a database, for various *uses cases* and one template need was to use `markdown`. 

I was surprised to see that all proposed `markdown` engines ( or I missed the one that could)
do not support *locals* or *scope* level expansions.

At least a better documentation should outline this, or partition the list in `templates engine` and `converters` as the proposed ``<% yield %>` only make sense, if this kind of **inclusion** mechanism is documented as a sort of **chain** operation.

Then it could be easy to understand for example, that an engine (like `handlebars` or `erb`) could make the template classic role of expanding *local or scope level structures* and other `converters` handle the end of a `chain` handling a *placeholder* like the documented `<% yield %.`

A better option for an upgraded version, would be to support, a **template** expansion mechanism, that would take any `template syntaxes supported` and add a cross langage expansion (e.g `à la ERB or Handlebars`).

For now, reading on the included `tests` I didn't see any such *expansion* capabilities in a lot of proposed templates engines.

    note : it seems that `slim` does that with its `interpolate` method, where it could call back *Tilt* with *variables expansion* using an usual `#{variable or xxx.to_s}` syntax. Sound like a good idea.

**Comment by judofyr** [comment]
Tilt is only a interface between various template engines. It does not try to define specific syntax or enforce conventions for the template languages. This has some known disadvantages (as the one you've mentioned), but the advantage is that it can cover many more template engines, and they work exactly the same with or without using Tilt.

**Comment by nonnenmacher** [comment]
I agree but some of the proposed `engine` are not **template engine per se**, but `markup converter`.

The uniform interface, impose to have some sort of common approach to `variable interpolation` injected inside the proposed engine from Tilt.

If not, then Slim seems a more reasonable approach, as Tilt could be used from inside an other `template engine`, this seems convoluted as this is more a role that fit the wrapping environment (i.e Tilt) than a role devolved to an engine, Tilt is supposed to call to `render`.

The other option, would be to describe an perhaps simplify usage of `chain of template engine` on front of `converter`.

I solved part of my usage, as a chain of `handlebars template` feeding a  `markdown` converter which is weird, costly an overkill to me.

**Comment by judofyr** [comment]
Yes, it's true, and a bit unfortunate, that we have mixed template engines and markup converters. This forces us to use the features of the lowest common denominator. Tilt is also a widely used gem (~500k downloads a month) and I'm unlikely to add any new features soon.

However, my main objection to this proposal is that I can't see how to implement it without either (1) implementing custom syntax or (2) asking all markdown converters to support it. Option 1 is equivalent with your current solution and doesn't actually require any changes in Tilt.

**Comment by nonnenmacher** [comment]
yes I understand, and I don't see how to implement this appart with implementing a `sub-contract` inside the `render` call, where an *optional* `interpolate like` method could be called before actual `render` implementation.

But could be very powerful and retro-compatible with a lot of existing template at the cost of adding this intermediate `method call` or `respond_to?` equivalent test in all existing plug-ins.

Guess this could be a prospective update, that will add a lot of power.

For now I will live with my `chain` as this is an `asynchronous email response solution` where there is no such volume and time constraints that would require `compilation` benefits, that are also part of the problem.

Thanks for your answer, I leave it for you to close it as you wish.

**Comment by judofyr** [comment]
I'll close it, but I'll have it mind in the future.
