### ISSUE TITLE
Stylus extension

### ISSUE THREAD

**Issue by Announcement** [rtomayko/tilt#291]
Is it okay if I add stylus extension as tilt team?
I know it's common to consider that language as _dead_ but in my opinion it's still very alive and active and the community strongly contributes to it, but quite honestly the main reason I want it is because it looks very pleasing with the upstream package slim-template/slim when combined with my previous pull request to tilt #286

**Comment by judofyr** [comment]
Sure. Maybe you can add your name as a "responsible person" or something as well?
