### ISSUE TITLE
Ruby 2.4.0 bug 12782

### ISSUE THREAD

**Issue by yb66** [rtomayko/tilt#311]
Hi,

I've just upgraded to Ruby v2.4.0 and appear to have been bitten by the bug described [on the Ruby bug tracker](https://bugs.ruby-lang.org/issues/12782). 

> myproj/vendor/ruby/2.4.0/gems/tilt-2.0.6/lib/tilt/haml.rb:50:in `block in precompiled_postamble': Haml::Engine#precompiled_method_return_value at /opt/rubies/ruby-2.4.0/lib/ruby/2.4.0/forwardable.rb:156 forwarding to private method Haml::TempleEngine#precompiled_method_return_value

They appear to have decided to revert the change that caused it, but to add warnings, probably to nudge people to stop forwarding to private methods. I thought I'd be helpful and open this issue ahead of time. Or for it to be fixed immediately (no pressure;)

Regards,
iain

ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin13]
Tilt v2.0.6
Haml v4.0.7 and 5.0.0.beta.2

**Comment by judofyr** [comment]
Huh. This method is actually not a public API, but is kept in Haml because Tilt depends on them. We should sort this out with a proper API from Haml.

**Comment by yb66** [comment]
Okay. I'd love to contribute something but I've looked at both [Haml's](https://github.com/haml/haml/blob/master/lib/haml/template.rb#L16) and [Tilt's](https://github.com/rtomayko/tilt/blob/master/lib/tilt/haml.rb#L50) code and can't see why it's been structured that way. It'll take me some run throughs with Pry and some cursing to get it. My genius has a(nother) new limit. 

Shall I open an issue with Haml, leave this open here too…?

iain
