### ISSUE TITLE
babel-transpiler is not a dependency of Tilt

### ISSUE THREAD

**Issue by tra38** [rtomayko/tilt#313]
I wanted to compile .jsx files using Sprockets, so I installed ```react-jsx-sprockets```, which was dependent on Tilt. But then I got this error..

```
/Users/tariqali/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/
tilt-2.0.7/lib/tilt/babel.rb:2:in `require': cannot load such file
 -- babel/transpiler (LoadError)
```

I was able to fix this error by adding a new gem to my Gemfile:
```ruby
gem "babel-transpiler"
```

But I'm confused why Tilt didn't install the "babel-transpiler" dependency to begin with, since Tilt requires this gem. I know I have a Ruby version greater than 1.9.3, so this code in the Gemfile should have worked in adding the dependency:

```ruby
group :primary do
  gem 'builder'
  gem 'haml', '>= 2.2.11', '< 4'
  gem 'erubis'
  gem 'markaby'
  gem 'sass'

  if can_execjs
    gem 'less'
    gem 'coffee-script'
    gem 'livescript'
    gem 'babel-transpiler'
    gem 'typescript-node'
  end
end
```

In fact, it doesn't appear *any* dependency is being installed by Tilt. According to my Gemfile.lock:

```
tilt (2.0.7)
```

stands by itself, with no dependency whatsoever. I'm really confused and need your help in solving this issue instead of relying on a fragile hack that might need to be repeated if I have to, say, use Typescript.

**Comment by judofyr** [comment]
It's intentional that Tilt does not depend on any template engine. You should add `babel-transpiler` to your own Gemfile if you want to use the Babel template class. The README tells you what libraries are required in order to use the various template classes.

**Comment by judofyr** [comment]
To clarify: Tilt itself doesn't depend on `babel-transpiler`. You can use most parts of Tilt without having `babel-transpiler` installed and this is why it's not marked as a dependency.
