### ISSUE TITLE
Haml::TempleEngine: Option :outvar is invalid

### ISSUE THREAD

**Issue by joshuamcginnis** [rtomayko/tilt#316]
I'm using Sinatra ~2.0 with latest HAML and I'm getting this error / warning when running the server:

```
Haml::TempleEngine: Option :outvar is invalid
~/.rvm/gems/ruby-2.4.1/gems/tilt-2.0.7/lib/tilt/haml.rb:50:in `block in precompiled_postamble':
Haml::Engine#precompiled_method_return_value at ~/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:157
forwarding to private method Haml::TempleEngine#precompiled_method_return_value  
```

Any ideas on how to address the underlying issue?

**Comment by judofyr** [comment]
Maybe @k0kubun knows something about this?

**Comment by k0kubun** [comment]
We need to cut a new release to use https://github.com/rtomayko/tilt/pull/312.

**Comment by k0kubun** [comment]
My previous comment was for "forwarding to private method Haml::TempleEngine#precompiled_method_return_value".

I'll research for "Haml::TempleEngine: Option :outvar is invalid".

**Comment by k0kubun** [comment]
Umm, it seems that sinatra always sets such option and Haml <= 4 just ignored it. I'll fix it in Haml side later.

**Comment by clay-f** [comment]
sinatra 2.0.0
haml 5.0.1
`Haml::TempleEngine: Option :outvar is invalid`

```
~/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/tilt-2.0.7/lib/tilt/haml.rb:50:in `block in 
precompiled_postamble': Haml::Engine#precompiled_method_return_value at 
/Users/Who/.rbenv/versions/2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to 
private method Haml::TempleEngine#precompiled_method_return_value
```
<img width="988" alt="screen shot 2017-07-24 at 00 02 49" src="https://user-images.githubusercontent.com/16079417/28500932-e31a0604-7003-11e7-89ac-7b96849d7359.png">

+1

**Comment by judofyr** [comment]
I've just released Tilt 2.0.8 which includes this fix

**Comment by marnen** [comment]
Still happening with Tilt 2.0.8 and Haml 5.0.4.

**Comment by k0kubun** [comment]
This issue is for Sinatra and https://github.com/rtomayko/tilt/pull/317 is for it too. Middleman is another problem.

**Comment by marnen** [comment]
@k0kubun I thought the issue was how Tilt calls Haml, not how Tilt itself is called, no? If that's so, then Sinatra/Middleman/Rails/whatever should be irrelevant. 

(If I'm wrong and the issue is how Middleman is calling Tilt, then I'll see what I can do to fix that)

**Comment by k0kubun** [comment]
That's because "how Tilt calls Haml" depends on how Sinatra/Middleman/Rails/whatever calls Tilt. In https://github.com/rtomayko/tilt/pull/317, it refers to `:outvar` option and it's passed by Sinatra as long as I remember.

I don't look into Middleman, so it may not be the case though. But I believe at least it's not reproductive with Sinatra, and you should confirm reproductivity using Sinatra for this issue.

**Comment by k0kubun** [comment]
I fixed your problem in https://github.com/middleman/middleman/pull/2149. You can see why middleman was not fixed by https://github.com/rtomayko/tilt/pull/317.
