### ISSUE TITLE
How to remove mapping

### ISSUE THREAD

**Issue by naokazuterada** [rtomayko/tilt#330]
Hi, I'm using tilt within [middleman](https://github.com/middleman/middleman).

In my situation, I don't want '.rst' files in my source to path renderer, and want to remove 'rst' from mappings.

I found the good tips [here](https://github.com/middleman/middleman/issues/822) like...

```
Tilt.mappings.delete('rst')
```

But this couldn't work, maybe because it's for the older version of tilt.
I'm using tilt v2.0.8.

I looked into source code, but couldn't find the way to remove the specific mapping from outside.
Any idea?

Thank you.

**Comment by judofyr** [comment]
The default mapping-object `Tilt.default_mapping` will change between point releases and it's mainly there for convenience and as a sensible default. If you need more control you should create a custom mappings object yourself (it's always better to whitelist than to blacklist):

```ruby
mapping = Tilt::Mapping.new
mapping.register(Tilt::ERBTemplate, 'erb')
```

It's a bit unfortunate if Middleman doesn't support a custom `Mapping`-object. I guess a temporary hack would be to override the `Tilt.default_mapping` method to return your custom object:

```ruby
Tilt.define_singleton_method(:default_mapping) { mapping }
```

**Comment by naokazuterada** [comment]
Thank you for quick response!
I found it works fine, but unfortunately it doesn't in the middleman env. Maybe the hook timing is the problem, I think. I will ask in the middleman's forum. Thank you anyway! I'm appreciate it.

**Comment by jeremyevans** [comment]
While it probably is better to use a custom mapping. It appears to be possible to modify the default mapping using the existing public API: `Tilt.default_mapping.lazy_map.delete('rst')`

**Comment by judofyr** [comment]
A `Mapping#unregister(*extensions)` method which both clears from `lazy_map` and from `template_map` does seem like a sensible addition to the API.

**Comment by jeremyevans** [comment]
I submitted #376 to implement `Mapping#unregister(*extensions)`
