### ISSUE TITLE
Push tag v2.0.9

### ISSUE THREAD

**Issue by MITSUBOSHI** [rtomayko/tilt#338]
Hi, it seems tilt v2.0.9 is available.
https://rubygems.org/gems/tilt/versions/2.0.9
However, there is no tags for v2.0.9 on GitHub. Could you push it?

(@rmm5t also already commented it here: https://github.com/rtomayko/tilt/commit/24aff97a5de62b0184b62ebf68196c0d4f2c71d9)

**Comment by judofyr** [comment]
Pushed now. Thanks for letting me know, it's very appreciated!
