### ISSUE TITLE
How do you pass Redcarpet render options through Tilt?

### ISSUE THREAD

**Issue by ky1007** [rtomayko/tilt#344]
I'm trying to pass Redcarpet render options through Tilt but not sure where to pass in my options. (I saw that this is supported via this issue: https://github.com/rtomayko/tilt/issues/238).

In my rails application I have `Tilt.prefer Tilt::RedcarpetTemplate` in `sprockets.rb`. Since I'm passing in the class `Tilt::RedcarpetTemplate` itself and not an instance of that class, I'm not sure how to pass options through

**Comment by jeremyevans** [comment]
Tilt supports this via: `Tilt::RedcarpetTemplate.new(file, 1, redcarpet_options)`

I expect your question is how to pass the options using sprockets, which is a question for sprockets, not for tilt.

**Comment by judofyr** [comment]
Unfortunately I don't have any clue how Sprockets is Tilt either.

Closing this since there's not much we can do from our side.
