### ISSUE TITLE
Pug support

### ISSUE THREAD

**Issue by noraj** [rtomayko/tilt#346]
Pug is a JavaScript templating language equivalent to slim, with a similar syntax.

But pug is much powerful and featureful with mixins, block and extends (template inheritance), etc.

Hopefully there is [pug-ruby](https://github.com/yivo/pug-ruby) that allow to compile Jade and Pug templates from Ruby.

Other leads are:
- [pug-rails](https://github.com/yivo/pug-rails)
- [jekyll-pug](https://github.com/DougBeney/jekyll-pug)
- [Jekyll-Bliss](https://github.com/DougBeney/Jekyll-Bliss) ([website](https://jekyll-pug.dougie.io/))

**Comment by jeremyevans** [comment]
pug-ruby appears to be dead dead upstream, no commits in about 4 years.  I think we should close this.

**Comment by noraj** [comment]
Seem that [jekyll-pug](https://github.com/DougBeney/jekyll-pug) survived but it's requiring [pug-ruby](https://github.com/yivo/pug-ruby).

**Comment by noraj** [comment]
But anyway as stated here https://github.com/yivo/pug-ruby/issues/5 we can't use ruby in the template so it would never be a true replacement for Slim.
