### ISSUE TITLE
Not support all options for CommonMarker

### ISSUE THREAD

**Issue by genghis-yang** [rtomayko/tilt#363]
Hi folks, first, thanks for all your contribution to this project. It's awesome.

Then, I have a question about CommonMarker. Seems CommonMarker support outdated. I need to pass some parse options through tilt to CommonMarker. But tilt only support one parse option `SMART`. All of other options are not supported.

I noticed @movermeyer has merged a PR #362 to support all options for CommonMarker recently. I believe it could resolve my problem. But I cannot use it directly because it hadn't released.

**Do you have any plan to release a new version recently?** I'm eager to get a full support version for CommonMarker. Thanks in advance 😄

**Comment by jeremyevans** [comment]
This can be closed as there was a recent 2.0.11 release.
