### ISSUE TITLE
Haml::TempleEngine: Option :line is invalid

### ISSUE THREAD

**Issue by mishina2228** [rtomayko/tilt#386]
I upgraded Haml to [v6.0.0](https://github.com/haml/haml/releases/tag/v6.0.0) and got the following warning:
```
Haml::TempleEngine: Option :line is invalid
```

The following codes may be relevant.
https://github.com/rtomayko/tilt/blob/56e78dac1e4e8862209e60e8259acf82ac5946c3/lib/tilt/haml.rb#L12-L20

**Comment by jeremyevans** [comment]
Thanks for the report. Looks like `haml` ships with it's own tilt handler now (`Haml::Template`).  Not sure why the handler that ships with Tilt is being used, unless you are referencing Tilt::HamlTemplate directly.

I'll submit a pull request to fix the warning and one spec failure.

**Comment by mishina2228** [comment]
Thank you for quick reply!
I dig into this problem a little, and I found something.

My source code was like this:
```ruby
require 'tilt'

Tilt.new('sample.haml')
```

Running the above code will display `Haml::TempleEngine: Option :line is invalid` warning.
Then I replaced `require 'tilt'` with `require 'haml'`, the warning disappeared.
```ruby
require 'haml'

Tilt.new('sample.haml')
```

It seems to be due to the different classes of instances returned by `Tilt.new`.
```
$ touch sample.haml
$ ruby -r tilt -e 'p Tilt.new("sample.haml").class'
Haml::TempleEngine: Option :line is invalid
Tilt::HamlTemplate
$ ruby -r haml -e 'p Tilt.new("sample.haml").class'
Haml::Template
```
