### ISSUE TITLE
Can we have a Gem release of the current state of Tilt?

### ISSUE THREAD

**Issue by hmdne** [rtomayko/tilt#390]
I have encountered an issue with Opal support while amending a TryRuby application. More precisely, what we need is this commit: https://github.com/rtomayko/tilt/commit/686cafab78f17ab04c82036ffb29db26ecad15f3

**Comment by jeremyevans** [comment]
I would definitely like a new tilt release.  I can work on a pull request that merges the existing pull requests, updates the Changelog, and bumps the version, assuming @judofyr is OK with that approach.

**Comment by jeremyevans** [comment]
Tilt 2.1.0 was released this morning.

**Comment by hmdne** [comment]
Thanks!
