### ISSUE TITLE
Erubis, Maraku and WikiCloth are unavailable in tilt 2.5

### ISSUE THREAD

**Issue by 3ynm** [rtomayko/tilt#398]
I am working on upgrading an old project. It uses erubis, and I notice that when I download the 2.5.0 gem, it does not include the `erubis.rb`, `maruku.rb` or `wikicloth.rb` files in `lib/`, but the 2.4.0 version does. Since this is not announced in the changelog, and the files are still available in the source code, I guess this is not intended.

**Comment by dentarg** [comment]
It is intended and noted at https://github.com/jeremyevans/tilt/blob/master/CHANGELOG.md#250-2024-12-20

Unfortunately this old tilt repo we're communicating in now hasn't been updated to properly direct traffic to the new repo: https://github.com/rtomayko/tilt/pull/395

(The current maintainer doesn't have commit access here)

**Comment by 3ynm** [comment]
Oh, ok.
