### ISSUE TITLE
Can't get rid of 'tilt autoloading' warning

### ISSUE THREAD

**Issue by leifbladt** [rtomayko/tilt#95]
I use EJS templates and can't get rid of the following warning even if a require EJS explicitly.

<pre>
WARN: tilt autoloading 'ejs' in a non thread-safe way; explicit require 'ejs' suggested.
</pre>

I'm not very familiar with multi-threading and requiring libs, but I found the following code: [template.rb](https://github.com/rtomayko/tilt/blob/master/lib/tilt/template.rb#L104-L107). When I understand the conditional right, the only check is, if there are more than one threads and not whether the lib was already loaded.

**Comment by burlesona** [comment]
Is this also true with `sass`? I'm getting the same message even with an explicit `require "sass"` before sprockets is required (Sinatra Project, using Sprockets 2.13.3)

**Comment by seddy** [comment]
@burlesona - I'm also seeing this on a Rails project (Sprockets 2.12.3), were you able to resolve that somehow?

**Comment by chrchr** [comment]
Here's my solution

```ruby
# This monkey patch kills Tilt's "WARN: tilt autoloading . . . " thing. 
# It does so by eliminating Tilt's ability to autoload stuff, so please
# explicitly require any template engines you want to use!

module Tilt
  class Template
    def require_template_library(name)
    end
  end
end
```
